### ISSUE TITLE
Fails to run on custom port

### ISSUE THREAD

**Issue by breznak** [numenta/cell-viz#32]
as 8080 is taken by nupic-history. 

```
cell-viz$ npm start 8081

> cell-viz@1.0.0 start /mnt/store/devel/HTM/htm_schools/cell-viz
> webpack-dev-server "8081"

/mnt/store/devel/HTM/htm_schools/cell-viz/node_modules/webpack/bin/convert-argv.js:558
                                var i = content.indexOf("=");
                                                ^

TypeError: content.indexOf is not a function
    at /mnt/store/devel/HTM/htm_schools/cell-viz/node_modules/webpack/bin/convert-argv.js:558:21
    at Array.forEach (native)
    at processOptions (/mnt/store/devel/HTM/htm_schools/cell-viz/node_modules/webpack/bin/convert-argv.js:557:11)
    at processConfiguredOptions (/mnt/store/devel/HTM/htm_schools/cell-viz/node_modules/webpack/bin/convert-argv.js:104:4)
    at module.exports (/mnt/store/devel/HTM/htm_schools/cell-viz/node_modules/webpack/bin/convert-argv.js:83:9)
    at Object.<anonymous> (/mnt/store/devel/HTM/htm_schools/cell-viz/node_modules/webpack-dev-server/bin/webpack-dev-server.js:68:48)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)

npm ERR! Linux 4.10.0-20-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start" "8081"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! cell-viz@1.0.0 start: `webpack-dev-server "8081"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cell-viz@1.0.0 start script 'webpack-dev-server "8081"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the cell-viz package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack-dev-server "8081"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs cell-viz
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls cell-viz
npm ERR! There is likely additional logging output above.
```

**Comment by rhyolight** [comment]
Wait a minute. I was mistaken when I told you to install webpack locally. `npm uninstall webpack` to get rid of it.

**Comment by breznak** [comment]
so only global?

Uninstalled both, installed only global, still get on custom port:
```
> cell-viz@1.0.0 start /mnt/store/devel/HTM/htm_schools/cell-viz
> webpack-dev-server "8081"

module.js:328
    throw err;
    ^

Error: Cannot find module 'webpack'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/mnt/store/devel/HTM/htm_schools/cell-viz/node_modules/webpack-dev-server/bin/webpack-dev-server.js:17:15)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)

npm ERR! Linux 4.10.0-20-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start" "8081"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! cell-viz@1.0.0 start: `webpack-dev-server "8081"`
npm ERR! Exit status 
```

**Comment by rhyolight** [comment]
I see. You don't need to run the webpack server. Just go to root and type `webpack`. This bundles the file for you offline.

**Comment by rhyolight** [comment]
Just to be clear, ignore the local server in cell-viz. It was just to show examples. Just run `webpack` and soft link to the file from htm-school-viz.

**Comment by breznak** [comment]
I know. Just a separate report that it cannot run on custom port, if that's non-issue we can close this. 
- [x] got the webpack running in this thread
